export const GET_DEVICE_A_DATA = "GET_DEVICE_A_DATA";
export const GET_DEVICE_B_DATA = "GET_DEVICE_B_DATA";
export const GET_DEVICE_C_DATA = "GET_DEVICE_C_DATA";

export const GET_COMBINED_DATA = "GET_COMBINED_DATA";

export const GET_WINDY_DAY = "GET_WINDY_DAY";
